<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="Latitude-E5570" name="tests.Tasks" tests="6" failures="0" timestamp="20 May 2019 01:21:43 GMT" time="0.001" errors="1">
  <testcase name="testPageTitle" time="0.001" classname="tests.Tasks">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at pages.SignInPage.clickOnSignButton(SignInPage.java:30)
at pages.SignInPage.signinWithCredentials(SignInPage.java:74)
at tests.Tasks.testPageTitle(Tasks.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testPageTitle -->
  <testcase name="newWindowMessage" time="0.000" classname="tests.Tasks">
    <skipped/>
  </testcase> <!-- newWindowMessage -->
  <testcase name="doTasks" time="0.000" classname="tests.Tasks">
    <skipped/>
  </testcase> <!-- doTasks -->
  <testcase name="printDate" time="0.000" classname="tests.Tasks">
    <skipped/>
  </testcase> <!-- printDate -->
  <testcase name="printTextFromAutocomplete" time="0.000" classname="tests.Tasks">
    <skipped/>
  </testcase> <!-- printTextFromAutocomplete -->
  <testcase name="printRandomTextFromAutocomplete" time="0.000" classname="tests.Tasks">
    <skipped/>
  </testcase> <!-- printRandomTextFromAutocomplete -->
</testsuite> <!-- tests.Tasks -->
